# Generated by Django 6.1 on 2026-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=400)),
                ('idea', models.CharField(max_length=400)),
                ('subject', models.TextField()),
                ('reference', models.FileField(blank=True, null=True, upload_to='references/')),
            ],
        ),
    ]
